grafana:
  enabled: true
  route:
    enabled: true
    host: grafana.lab.local

prometheus:
  prometheusSpec:
    retention: 7d
  route:
    enabled: true
    host: prometheus.lab.local

gateway:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web
    namespace: infra
    sectionName: web