apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vault
  namespace: argocd

spec:
  project: security
  
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: platform/security/vault
    helm:
      releaseName: vault
      

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

