apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodegoat-deployment
  labels:
    {{- include "nodegoat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodegoat.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        {{- include "nodegoat.labels" . | nindent 8 }}
    spec:
      containers:
      - name: nodegoat
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/nodegoat
        command:
          - /bin/sh
          - -c
          - |
            until nc -z mongodb 27017; do
              sleep 2
            done
            node artifacts/db-reset.js
            exec npm start