apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: demo
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: mongodb-auth

  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: mongo
        property: uri-hieu