apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: nodegoat
spec:
  parentRefs:
    - name: web
      namespace: infra
      sectionName: web

  hostnames:
    - {{ .Values.route.host | quote }}

  rules:
    - backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}