{{- if .Values.dbInitJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: nodegoat-db-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init-db
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
          - /bin/sh
          - -c
          - |
            until nc -z -w 2 mongodb.platform.svc.cluster.local 27017; do
              sleep 2
            done
            node artifacts/db-reset.js
        envFrom:
        - secretRef:
            name: mongodb-auth
{{- end }}