kube-prometheus-stack:
  grafana:
    enabled: true
    persistence:
      enabled: true
      storageClassName: longhorn-standard
      size: 1Gi
    admin:
      existingSecret: grafana-admin5
      userKey: grafana-user
      passwordKey: grafana-password
    
    additionalDataSources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        editable: true

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: false
        editable: true

  prometheus:
    prometheusSpec:
      retention: 1d
      retentionSize: 1500MB
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 512Mi
  
  kubelet:
    serviceMonitor:
      resourceInterval: 30s
      cAdvisorInterval: 30s

route:
  grafana:
    enabled: true
    host: grafana.lab.internal
  prometheus:
    enabled: true
    host: prometheus.lab.internal

gateway:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web
    namespace: gateway
    sectionName: web