loki:
  deploymentMode: Monolithic

  defaults:
    extraEnvFrom:
      - secretRef:
          name: loki-minio

    extraArgs:
      - -config.expand-env=true
      
  singleBinary:
    persistence:
      size: 2Gi
      storageClass: longhorn-dev

  loki:
    auth_enabled: false

    commonConfig:
      replication_factor: 1

    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler

      use_thanos_objstore: true
      
      object_store:
        type: s3
        storage_prefix: dev
        s3:
          region: us-east-1
          endpoint: ${AWS_ENDPOINT}
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          insecure: true

    schemaConfig:
      configs:
        - from: "2026-07-08"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

  chunksCache:
    allocatedMemory: 256
    allocatedCPU: 100m

    l2:
      enabled: false
      allocatedMemory: 128
      allocatedCPU: 100m

  resultsCache:
    allocatedMemory: 128
    allocatedCPU: 100m