apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: loki-minio

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio
        property: user

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio
        property: pass

    - secretKey: AWS_ENDPOINT
      remoteRef:
        key: minio
        property: host