apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: metrics
  namespace: argocd

spec:
  project: observability
  
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: platform/observability/metrics
    helm:
      releaseName: metrics
      

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

