apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nodegoat
  namespace: argocd

spec:
  project: apps
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: apps/nodegoat
    helm:
      releaseName: nodegoat

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true