apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: minio-secret

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio
        property: user

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio
        property: pass

    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: minio
        property: host