apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb
  namespace: platform
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore

  target:
    name: mongodb-auth

  data:
    - secretKey: username
      remoteRef:
        key: mongo
        property: username

    - secretKey: password
      remoteRef:
        key: mongo
        property: password

    - secretKey: rootPassword
      remoteRef:
        key: mongo
        property: rootPassword