longhorn:
  route:
    enabled: true
    host: longhorn.lab.local

  metrics:
    serviceMonitor:
      enabled: true

  defaultSettings:
    defaultReplicaCount: 1
    storageReservedPercentageForDefaultDisk: 60 
    storageMinimalAvailablePercentage: 10

  preUpgradeChecker:
    jobEnabled: false

gateway:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: web
    namespace: infra
    sectionName: web



