apiVersion: helm.cattle.io/v1
kind: HelmChartConfig

metadata:
  name: traefik
  namespace: kube-system

spec:
  valuesContent: |-
    providers:
      kubernetesGateway:
        enabled: true
    
    tracing:
      serviceName: traefik

      otlp:
        enabled: true

        grpc:
          enabled: true
          endpoint: collector-opentelemetry-collector.monitoring.svc.cluster.local:4317
          insecure: true