apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: longhorn
  namespace: argocd

spec:
  project: storage
  
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: platform/storage/longhorn
    helm:
      releaseName: longhorn
      

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

