apiVersion: v2

name: Authentik

description: A Helm chart for deploying Authentik

type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: authentik
    repository: https://charts.goauthentik.io
    version: 2026.5.4
