apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: Storage
  namespace: argocd

spec:
  project: storage
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: gitops/applications/storage 

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 