apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: gateway-api
  namespace: argocd

spec:
  project: networking
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: platform/networking/gateway
    helm:
      releaseName: gateway-api

  destination:
    server: https://kubernetes.default.svc
    namespace: gateway

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true