apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: traefik-custom
  namespace: argocd

spec:
  project: networking
  source:
    repoURL: https://github.com/hieu190400/gitops-homelab
    targetRevision: main
    path: platform/networking/traefik 

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system 
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 